### ISSUE TITLE
No real guide - Question

### ISSUE THREAD

**Issue by FixingGlobe** [henkelmax/emoji#1]
Hi,
sorry to bother you, but this mod has no guide so I'm not exactly sure how to open the emoji popup.
Installed client side, removed all other mods and just left the api and I really don't know how to get the popup.

**Comment by henkelmax** [comment]
This mod is not meant to be used by other people. It was made for one specific purpose and requires a special resource pack.
The popup can be opened when in a text field with `CTRL + .` but it won't show anything with a resource pack.
